language: python

python:
  - "2.7"
  - "3.4"

env:
  global: DJANGO_SETTINGS_MODULE="django_whoshere.tests.settings"
  - DJANGO=1.8.1
  - DJANGO=1.7.8

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py install

before_script:
  - django-admin migrate
script:
  - django-admin test
services:
  - redis