language: python

python:
  - "2.7"
  - "3.4"

env:
    - DJANGO=1.8.5
    - DJANGO=1.7.10

install:
  - pip install -q django==$DJANGO
  - pip install pyyaml ua-parser user-agents coveralls
  - python setup.py install

script:
  - coverage run --source=django_whoshere setup.py test

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8501ffb8d6faf9652e30
    on_success: change
    on_failure: always
    on_start: false
